- .github/workflows/ci-maven-publish-release.yaml
- .github/workflows/dispatch-build-test-image.yaml
- .github/workflows/pr-build-and-test.yml
- README.md
- client/pom.xml
- pom.xml
The protoc version should match the used protobuf-java version. See https://protobuf.dev/support/cross-version-runtime-guarantee/. That's why it's better to manage the protoc version as part of the build.
There's a dependency between grpc and protobuf too. The compatible protobuf-java version for the respective grpc-protobuf version can be looked up in the the pom file in https://repo1.maven.org/maven2/io/grpc/grpc-protobuf/ and looking for the protobuf-java version in that file. For grpc 1.59.0, the pom file is https://repo1.maven.org/maven2/io/grpc/grpc-protobuf/1.59.0/grpc-protobuf-1.59.0.pom . It depends on protobuf-java 3.24.0 .
> Manage protoc version as part of the build

- client-api/src/main/java/io/streamnative/oxia/client/api/AsyncOxiaClient.java
- client-api/src/main/java/io/streamnative/oxia/client/api/DeleteOption.java
- client-api/src/main/java/io/streamnative/oxia/client/api/OptionEphemeral.java
- client-api/src/main/java/io/streamnative/oxia/client/api/OptionVersionId.java
- client-api/src/main/java/io/streamnative/oxia/client/api/SyncOxiaClient.java
- client-it/src/test/java/io/streamnative/oxia/client/it/OxiaClientIT.java
- client/src/main/java/io/streamnative/oxia/client/AsyncOxiaClientImpl.java
- client/src/main/java/io/streamnative/oxia/client/CachingAsyncOxiaClient.java
- client/src/main/java/io/streamnative/oxia/client/DeleteOptionsUtil.java
- client/src/main/java/io/streamnative/oxia/client/PutOptionsUtil.java
- client/src/main/java/io/streamnative/oxia/client/SyncOxiaClientImpl.java
- client/src/main/java/io/streamnative/oxia/client/batch/Operation.java
- client/src/test/java/io/streamnative/oxia/client/AsyncOxiaClientImplTest.java
- client/src/test/java/io/streamnative/oxia/client/CachingAsyncOxiaClientTest.java
- client/src/test/java/io/streamnative/oxia/client/api/DeleteOptionTest.java
- client/src/test/java/io/streamnative/oxia/client/api/PutOptionTest.java
- client/src/test/java/io/streamnative/oxia/client/batch/BatchTest.java
- client/src/test/java/io/streamnative/oxia/client/batch/BatcherTest.java
- client/src/test/java/io/streamnative/oxia/client/batch/OperationTest.java
- pulsar-metadatastore-oxia/src/main/java/io/streamnative/pulsarmetadatastoreoxia/OxiaMetadataStore.java
* Avoid expensive allocations during validation in the hot path
* Take `Set<PutOption>` instead of `PutOption...` because it will make it easier for complex wrappers to use
> Refactored Put & Delete options

- client/src/main/java/io/streamnative/oxia/client/shard/ShardManager.java
- client/src/test/java/io/streamnative/oxia/client/shard/ShardManagerTest.java
https://github.com/streamnative/oxia-java/issues/170
Oxia-java client didn't handle well with unchanged assignments. which calls the `toMap` method with the duplicated key and causes an exception throw in the GRPC stream.
The real exception capture by Arthas
```
java.lang.IllegalStateException: Duplicate key 36 (attempted merging values Shard[id=36, leader=***********, hashRange=HashRange[minInclusive=0, maxInclusive=4294967295]] and Shard[id=36, leader=***********, hashRange=HashRange[minInclusive=0, maxInclusive=4294967295]])
```
Why can the client receive notification about unchanged assignments?
1. The coordinator sends node-level assignments to the oxia server.
2. The oxia server will filter the namespace without an equals check and then send it to the client. (maybe caused by …
> shardsManager: fix unchanged shard assignment causes exception

- client/src/main/java/io/streamnative/oxia/client/grpc/OxiaStub.java
I observe we have some connection issue when restart oxia server that causes the client can't work.  the client consist print error logs like:
```
Caused by: java.net.UnknownHostException: xxxxxxxxx: Name does not resolve
at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Unknown Source)
at java.base/java.net.InetAddress$PlatformResolver.lookupByName(Unknown Source)
at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
at java.base/java.net.InetAddress.getAllByName(Unknown Source)
at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(Dns …
```
> fix: fix unrecovery channel exception

- client-it/src/test/java/io/streamnative/oxia/client/it/ClientReconnectIT.java
- client/src/main/java/io/streamnative/oxia/client/batch/WriteStreamWrapper.java
- client/src/main/java/io/streamnative/oxia/client/grpc/OxiaStub.java
- testcontainers/src/main/java/io/streamnative/oxia/testcontainers/OxiaContainer.java
the current implementation didn't replace the failed stream to a new stream. that causes client constantly get exception when write data to server due to oxia server restart.
- Replace the invalid stream with a new one.
I am considering the performance affection here, let us try improve in the future.
> fix: fix write stream reconnection issue

- client/src/main/java/io/streamnative/oxia/client/shard/ShardManager.java
In the today's testing, we got a not useful log. it's better to improve it.
- Print the exception when got an error.
> feat: improve error log when get shards assignments

- client-api/src/main/java/io/streamnative/oxia/client/api/OxiaClientBuilder.java
- client/pom.xml
- client/src/main/java/io/streamnative/oxia/client/AsyncOxiaClientImpl.java
- client/src/main/java/io/streamnative/oxia/client/ClientConfig.java
- client/src/main/java/io/streamnative/oxia/client/OxiaClientBuilderImpl.java
- client/src/main/java/io/streamnative/oxia/client/grpc/OxiaBackoffProvider.java
- client/src/main/java/io/streamnative/oxia/client/grpc/OxiaStub.java
- client/src/main/java/io/streamnative/oxia/client/grpc/OxiaStubManager.java
- client/src/main/java/io/streamnative/oxia/client/util/Backoff.java
- client/src/test/java/io/streamnative/oxia/client/batch/BatchTest.java
- client/src/test/java/io/streamnative/oxia/client/batch/BatcherTest.java
- client/src/test/java/io/streamnative/oxia/client/grpc/OxiaStubTest.java
- client/src/test/java/io/streamnative/oxia/client/session/SessionTest.java
The GRPC default backoff is from 2s to 120s, which is very long for time sensitive usage.
Using reflection to replace the existing backoff here due to that is not configurable.
FYI: https://github.com/grpc/grpc-java/issues/10932#issuecomment-1954913671
> feat: improve the reconnection backoff

- client-api/src/main/java/io/streamnative/oxia/client/api/Notification.java
- client-it/src/test/java/io/streamnative/oxia/client/it/NotificationIt.java
- client/src/main/java/io/streamnative/oxia/client/notify/ShardNotificationReceiver.java
- client/src/main/proto/io/streamnative/oxia/client.proto
Support `deleteRange` notification. see https://github.com/streamnative/oxia/pull/532
> feat(notification): support deleteRange notification

- client/src/main/java/io/streamnative/oxia/client/session/SessionManager.java
- client/src/test/java/io/streamnative/oxia/client/session/SessionManagerTest.java
Avoid cache exceptional sessions creation future to allow retry next time.
> fix(session): avoid cache exceptional session creation future

- client-api/src/main/java/io/streamnative/oxia/client/api/OxiaClientBuilder.java
- client-it/src/test/java/io/streamnative/oxia/client/it/NotificationIt.java
- client-it/src/test/java/io/streamnative/oxia/client/it/OxiaClientFailFastIT.java
- client-it/src/test/java/io/streamnative/oxia/client/it/OxiaClientIT.java
- client/src/main/java/io/streamnative/oxia/client/AsyncOxiaClientImpl.java
- client/src/main/java/io/streamnative/oxia/client/ClientConfig.java
- client/src/main/java/io/streamnative/oxia/client/OxiaClientBuilderImpl.java
- client/src/main/java/io/streamnative/oxia/client/batch/BatchBase.java
- client/src/main/java/io/streamnative/oxia/client/batch/WriteBatch.java
- client/src/main/java/io/streamnative/oxia/client/grpc/OxiaStub.java
- client/src/main/java/io/streamnative/oxia/client/grpc/OxiaStubManager.java
- client/src/main/java/io/streamnative/oxia/client/grpc/OxiaStubProvider.java
- client/src/main/java/io/streamnative/oxia/client/grpc/OxiaWriteStreamManager.java
- client/src/main/java/io/streamnative/oxia/client/grpc/WriteStreamKey.java
- client/src/main/java/io/streamnative/oxia/client/grpc/WriteStreamWrapper.java
- client/src/test/java/io/streamnative/oxia/client/batch/BatchTest.java
- client/src/test/java/io/streamnative/oxia/client/batch/BatcherTest.java
- client/src/test/java/io/streamnative/oxia/client/grpc/OxiaStubTest.java
- client/src/test/java/io/streamnative/oxia/client/notify/NotificationManagerTest.java
- client/src/test/java/io/streamnative/oxia/client/notify/ShardNotificationReceiverTest.java
- client/src/test/java/io/streamnative/oxia/client/session/SessionTest.java
- client/src/test/java/io/streamnative/oxia/client/shard/ShardManagerGrpcTest.java
Currently, we are using `directExecutor`(Transport executor) to do the RPC callback. And every node only has a single channel with a single thread. That is easily exhausted. We can use multiple channels for better performance improvement.
- support `maxConnectionPerNode` configuration
- extract write stream logic and make it not bind with specific stub.
- set multiple connection per node for some integration tests.
> feat(stub): support multiple connection per node

- client/src/main/java/io/streamnative/oxia/client/batch/ReadBatch.java
- client/src/main/java/io/streamnative/oxia/client/grpc/WriteStreamWrapper.java
in the GRPC stream, if the server normally closes the stream without a response. the client will have a pending request forever. we can fast fail that request in the case.
> feat(stream): fail pending request if server close stream without response

- pom.xml
- pulsar-metadatastore-oxia/pom.xml
- pulsar-metadatastore-oxia/src/main/java/io/streamnative/pulsarmetadatastoreoxia/OxiaMetadataStore.java
- pulsar-metadatastore-oxia/src/test/java/io/streamnative/pulsarmetadatastoreoxia/OxiaMetadataStoreTest.java
- pulsar-metadatastore-oxia/src/test/java/io/streamnative/pulsarmetadatastoreoxia/bookkeeper/OxiaLedgerUnderreplicationManagerTest.java
- pulsar-metadatastore-oxia/src/test/java/io/streamnative/pulsarmetadatastoreoxia/bookkeeper/OxiaPulsarRegistrationClientTest.java
- upgrade test dependencies to support building with Java 21
- cleanup build
- enables running pulsar-metadatastore-oxia tests
- tests were broken which means that they weren't run
- fix broken tests
- `OxiaMetadataStore.close` wasn't implemented properly.
- At shutdown time further operations wouldn't be aborted with `MetadataStoreException.AlreadyClosedException`.
- addresses this issue
> Add Java 21 build support and enable running of pulsar-metadatastore-oxia tests

- client/pom.xml
- pulsar-metadatastore-oxia/pom.xml
- javax.annotation:javax.annotation-api is deprecated
- replaces javax.annotation:javax.annotation-api with jakarta.annotation:jakarta.annotation-api
> Replace javax.annotations with jakarta.annotations

- client-it/pom.xml
- client-it/src/test/java/io/streamnative/oxia/client/it/NotificationIt.java
- client-it/src/test/java/io/streamnative/oxia/client/it/OxiaClientIT.java
- perf-ycsb/pom.xml
- perf/pom.xml
- pom.xml
- upgrade to OTel to 1.44.1
- migrate to use io.opentelemetry.semconv:opentelemetry-semconv since the previous dependency is discontinued
- use dependencyManagement to assign versions
> Upgrade OpenTelemetry library to 1.44.1

- client/src/main/java/io/streamnative/oxia/client/grpc/OxiaStub.java
Disable GRPC retry to avoid any data inconsistency since we have the write with the delta feature.
- disable GRPC retry.
> fix(grpc): disable transparent retry

- client/src/main/java/io/streamnative/oxia/client/grpc/OxiaWriteStreamManager.java
- client/src/main/java/io/streamnative/oxia/client/grpc/WriteStreamWrapper.java
This PR will improve the logic to avoid unnecessary locks and add a check when the stream is complete.
- lock-free first when getting the stream.
- Add check when the stream complete
> feat: avoid lock and add check when complete

- client/src/main/java/io/streamnative/oxia/client/grpc/WriteStreamWrapper.java
The internal `completed` status might overridden by the fail-fast stream. We should always make the `stub.writeStream(this)` at the end of the init logic. 
- Move the `stub.writeStream(this);` at the end of the init logic.
> fix: completed status overrided by fail-fast stream

- .github/workflows/pr-build-and-test.yml
- client/src/main/java/io/streamnative/oxia/client/AsyncOxiaClientImpl.java
- client/src/test/java/io/streamnative/oxia/client/AsyncOxiaClientImplTest.java
Supporting the default operation timeout to make the client lib more robust. The current default value is 30s and only supports common operations right now.(except streaming `rangeScan` and notification)
> feat: support request level default timeout for common operation

- client/src/main/java/io/streamnative/oxia/client/AsyncOxiaClientImpl.java
- client/src/test/java/io/streamnative/oxia/client/AsyncOxiaClientImplTest.java
Fix more than one `onError` callback from `rangeScan` interface. You can check [example.ranscan.callback](https://github.com/streamnative/oxia-java/tree/example.ranscan.callback) for reproduce.
- Be sure to call only once between `onCompleted` and `onError`.
- Reduce the code complexity.
> fix: range scan more than one onError callback

- client/src/main/java/io/streamnative/oxia/client/grpc/WriteStreamWrapper.java
Improve logs to avoid annoying users.
- Change `onCompleted ` logs level to `Info` and remove `completedException`.
- Avoid print stack trace for the `onError ` method because that is an async connection callback. the stack trace is useless.
> feat: avoid printing unexpected messages

- client-api/src/main/java/io/streamnative/oxia/client/api/GetOption.java
- client-api/src/main/java/io/streamnative/oxia/client/api/OptionIncludeValue.java
- client-it/src/test/java/io/streamnative/oxia/client/it/OxiaClientIT.java
- client/src/main/java/io/streamnative/oxia/client/AsyncOxiaClientImpl.java
- client/src/main/java/io/streamnative/oxia/client/batch/Operation.java
- client/src/main/java/io/streamnative/oxia/client/options/GetOptions.java
- client/src/test/java/io/streamnative/oxia/client/batch/BatchTest.java
- client/src/test/java/io/streamnative/oxia/client/batch/BatcherTest.java
- client/src/test/java/io/streamnative/oxia/client/batch/OperationTest.java
See https://github.com/streamnative/oxia/pull/636
> feat: support `IncludeValue` for get operation

- client-api/src/main/java/io/streamnative/oxia/client/api/GetOption.java
- client-api/src/main/java/io/streamnative/oxia/client/api/OptionSecondaryIndexName.java
- client-it/src/test/java/io/streamnative/oxia/client/it/OxiaClientIT.java
- client/src/main/java/io/streamnative/oxia/client/AsyncOxiaClientImpl.java
- client/src/main/java/io/streamnative/oxia/client/batch/Operation.java
- client/src/main/java/io/streamnative/oxia/client/options/GetOptions.java
- client/src/main/proto/io/streamnative/oxia/client.proto
- client/src/test/java/io/streamnative/oxia/client/batch/BatchTest.java
- client/src/test/java/io/streamnative/oxia/client/batch/BatcherTest.java
- client/src/test/java/io/streamnative/oxia/client/batch/OperationTest.java
(Depends on https://github.com/streamnative/oxia/pull/686)
> Support secondary index on point get operation

- client-api/src/main/java/io/oxia/client/api/AsyncOxiaClient.java
- client-api/src/main/java/io/oxia/client/api/DeleteOption.java
- client-api/src/main/java/io/oxia/client/api/DeleteRangeOption.java
- client-api/src/main/java/io/oxia/client/api/GetOption.java
- client-api/src/main/java/io/oxia/client/api/GetResult.java
- client-api/src/main/java/io/oxia/client/api/GetSequenceUpdatesOption.java
- client-api/src/main/java/io/oxia/client/api/ListOption.java
- client-api/src/main/java/io/oxia/client/api/Notification.java
- client-api/src/main/java/io/oxia/client/api/OptionSequenceKeysDeltas.java
- client-api/src/main/java/io/oxia/client/api/PutOption.java
- client-api/src/main/java/io/oxia/client/api/PutResult.java
- client-api/src/main/java/io/oxia/client/api/RangeScanOption.java
- client-api/src/main/java/io/oxia/client/api/SyncOxiaClient.java
- client-api/src/main/java/io/oxia/client/api/Version.java
- client-api/src/main/java/io/oxia/client/api/exceptions/KeyAlreadyExistsException.java
- client-api/src/main/java/io/oxia/client/api/exceptions/UnexpectedVersionIdException.java
The annotations are messing bit up the Javadocs
> Removed @NonNull annotations from public APIs
